language: java
script: mvn clean install
deploy:
  provider: heroku
  api_key: ${API_KEY}
  app: 
    master: emn-cloud-auth
env:
  global:
    - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
    - vcap.services.eureka-service.credentials.uri=${vcap.services.eureka-service.credentials.uri}
